const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.TiledBg,
		C3.Behaviors.Fade,
		C3.Plugins.Audio,
		C3.Plugins.Browser,
		C3.Plugins.Keyboard,
		C3.Plugins.Mouse,
		C3.Plugins.Touch,
		C3.Plugins.Arr,
		C3.Plugins.AJAX,
		C3.Plugins.LocalStorage,
		C3.Plugins.Particles,
		C3.Behaviors.Sin,
		C3.Behaviors.Bullet,
		C3.Plugins.Spritefont2,
		C3.Plugins.Json,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.MoveToBottom,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Arr.Acts.Clear,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.System.Exps.projectname,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Spritefont2.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Spritefont2.Cnds.CompareInstanceVar,
		C3.Plugins.Spritefont2.Acts.SetAngle,
		C3.Plugins.Spritefont2.Acts.SetScale,
		C3.Plugins.Spritefont2.Acts.SetCharacterSpacing,
		C3.Plugins.System.Cnds.IsMobile,
		C3.Plugins.TiledBg.Acts.SetAngle,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Arr.Acts.SetSize,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Spritefont2.Acts.SetY,
		C3.Plugins.Spritefont2.Exps.Y,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.Audio.Acts.SetPlaybackRate,
		C3.Plugins.TiledBg.Acts.SetPos,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.System.Exps.viewporttop,
		C3.Plugins.System.Exps.viewportbottom,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Exps.viewportleft,
		C3.Plugins.Spritefont2.Acts.SetPosToObject,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.System.Exps.viewportright,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.System.Acts.WaitForSignal,
		C3.Plugins.Sprite.Cnds.OnAnyAnimFinished,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Particles.Acts.SetAngle,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.Sprite.Acts.MoveToLayer,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Particles.Acts.SetPos,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.Sprite.Acts.StopAnim,
		C3.Plugins.Sprite.Acts.SetCollisions,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.TiledBg.Acts.SetInstanceVar,
		C3.Plugins.TiledBg.Acts.SetWidth,
		C3.Plugins.Sprite.Cnds.CompareHeight,
		C3.Plugins.Sprite.Cnds.CompareWidth,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Sprite.Exps.Opacity,
		C3.Plugins.TiledBg.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Cnds.CompareOpacity,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Sprite.Acts.RotateTowardAngle,
		C3.Plugins.System.Cnds.ForEach,
		C3.Behaviors.Bullet.Cnds.CompareSpeed,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Arr.Acts.Push,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Arr.Exps.Width,
		C3.Plugins.Arr.Acts.Delete,
		C3.Plugins.Arr.Exps.IndexOf,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.Arr.Cnds.Contains,
		C3.Plugins.System.Acts.CreateObject,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.Sprite.Acts.StartAnim,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.TiledBg.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Behaviors.Bullet.Acts.SetEnabled,
		C3.Plugins.Arr.Acts.SetX,
		C3.Plugins.Arr.Cnds.ArrForEach,
		C3.Plugins.Arr.Cnds.CompareCurrent,
		C3.Plugins.Arr.Exps.CurX,
		C3.Plugins.TiledBg.Acts.Destroy,
		C3.Behaviors.Fade.Acts.SetWaitTime,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Arr.Acts.JSONLoad,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.Arr.Exps.Depth,
		C3.Plugins.Arr.Exps.CurY,
		C3.Plugins.Arr.Cnds.CompareX,
		C3.Plugins.Arr.Exps.AsJSON,
		C3.Plugins.Spritefont2.Acts.AppendText,
		C3.Plugins.Arr.Exps.CurValue,
		C3.Plugins.Audio.Acts.Preload,
		C3.Plugins.System.Exps.loadingprogress,
		C3.Plugins.Spritefont2.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.System.Cnds.OnLoadFinished,
		C3.Plugins.Spritefont2.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Acts.SetAnimSpeed,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.AJAX.Acts.RequestFile,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.LocalStorage.Cnds.IsProcessingGets,
		C3.Plugins.Audio.Acts.SetVolume,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Acts.SetLayerOpacity,
		C3.Plugins.System.Acts.SetLayerScale,
		C3.Plugins.System.Exps.layeropacity,
		C3.Plugins.System.Exps.layerscale,
		C3.Plugins.Sprite.Cnds.CompareAnimSpeed,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Browser.Acts.RequestFullScreen,
		C3.Plugins.Browser.Acts.CancelFullScreen,
		C3.Plugins.Mouse.Cnds.IsButtonDown,
		C3.Plugins.Mouse.Acts.SetCursorSprite,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.System.Acts.Signal,
		C3.Plugins.System.Exps.windowwidth,
		C3.Plugins.System.Exps.windowheight,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.Spritefont2.Acts.SetPos,
		C3.Plugins.System.Cnds.LayerCmpOpacity,
		C3.Plugins.System.Exps.max,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.Browser.Acts.Close,
		C3.Plugins.Spritefont2.Acts.SetOpacity,
		C3.Plugins.Spritefont2.Exps.Opacity,
		C3.Plugins.Browser.Acts.GoToURLWindow,
		C3.Plugins.Sprite.Acts.SetEffectParam,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.Arr.Acts.SetXYZ,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.Arr.Acts.JSONDownload,
		C3.Plugins.LocalStorage.Acts.RemoveItem,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.Spritefont2.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Spritefont2.Acts.SetVisible
	];
};
self.C3_JsPropNameTable = [
	{Cursor: 0},
	{Cursor_Pressed: 0},
	{Gui_Big_Frame: 0},
	{Map: 0},
	{Gui_Controls_Player_1: 0},
	{Gui_Controls_Player_2: 0},
	{Name: 0},
	{Gui_Level: 0},
	{Frame_Glass_3: 0},
	{Gui_Total_Score: 0},
	{Curtain: 0},
	{Gui_Curtain_Frame: 0},
	{Gui_Kills_Player_1: 0},
	{Gui_Kills_Player_2: 0},
	{ID: 0},
	{Hide: 0},
	{Level_Closed: 0},
	{Gui_Score_Player_1: 0},
	{Gui_Score_Player_2: 0},
	{Gui_Life_Player_1: 0},
	{Gui_Life_Player_2: 0},
	{Gui_Levels_Frame: 0},
	{Enemy_Tank_Icons: 0},
	{Gui_Top_Frame: 0},
	{Gui_Enemy: 0},
	{state: 0},
	{Frame_Glass_1: 0},
	{Gui_Three_Button_Frame: 0},
	{Gui_Constructor_Function: 0},
	{Frame_Glass_2: 0},
	{Gui_One_Button_Frame: 0},
	{Gui_Two_Button_Frame: 0},
	{Gui_Score_Frame: 0},
	{Gui_Difficulty: 0},
	{Gui_Frame_0: 0},
	{Frame_Glass_0: 0},
	{Frame_Text: 0},
	{Level_Stars: 0},
	{Frame_Text_1: 0},
	{Frame_Text_2: 0},
	{Gui_Game_Over: 0},
	{Gui_Score: 0},
	{Gui_Star: 0},
	{Frame_Text_3: 0},
	{Frame_Text_4: 0},
	{Skull: 0},
	{Gui_Difficulty2: 0},
	{Frame_Cheat_Codes: 0},
	{Frame_Text_5: 0},
	{Frame_Help_1: 0},
	{Frame_Help_2: 0},
	{Frame_Help_3: 0},
	{Frame_Help_4: 0},
	{Frame_Help_5: 0},
	{Frame_Help_6: 0},
	{Frame_Help_7: 0},
	{Frame_Help_8: 0},
	{Frame_Help_9: 0},
	{Level_Star: 0},
	{Frame_Line: 0},
	{Loading_Line: 0},
	{Prize: 0},
	{Sun_Rays: 0},
	{Gui_Big_Frame2: 0},
	{Gui_One_Button_Frame2: 0},
	{Background: 0},
	{Game_Logo: 0},
	{Ground: 0},
	{Point: 0},
	{Enemy_Spawn: 0},
	{Tree_1: 0},
	{Life: 0},
	{Destroyed: 0},
	{Bridge: 0},
	{Base: 0},
	{Water: 0},
	{Player_1_Spawn: 0},
	{Brick: 0},
	{Iron: 0},
	{Steel_1: 0},
	{Steel_2: 0},
	{Steel_3: 0},
	{Steel_4: 0},
	{Player_2_Spawn: 0},
	{Base_Wall: 0},
	{Ground_Decor_1: 0},
	{Ground_Decor_2: 0},
	{Bridge_Water: 0},
	{Rivets_Bottom: 0},
	{Rivets_Top: 0},
	{Fade: 0},
	{Ice: 0},
	{Tree_2: 0},
	{Tree_3: 0},
	{Tree_4: 0},
	{Stump: 0},
	{Audio: 0},
	{Browser: 0},
	{Keyboard: 0},
	{Mouse: 0},
	{Touch: 0},
	{AvailableDirections: 0},
	{Levels: 0},
	{AJAX: 0},
	{Levels_Stars_JSON: 0},
	{Levels_Stars_LOCAL: 0},
	{Kill_Enemies: 0},
	{Levels_Score_JSON: 0},
	{Levels_Score_LOCAL: 0},
	{Cheat_Codes: 0},
	{LocalStorage: 0},
	{Explosion_Tank: 0},
	{Blasted_Tank: 0},
	{Explosion_Bullet: 0},
	{Smoke_Tank: 0},
	{Fire_Tank: 0},
	{Smoke_Dead: 0},
	{Sine: 0},
	{Glow_Dead: 0},
	{Fire_Dead: 0},
	{Smoke_Base: 0},
	{Drown_Tank: 0},
	{Explosion_Brick: 0},
	{Active: 0},
	{Shield: 0},
	{Drown: 0},
	{WidthSize: 0},
	{HeightSize: 0},
	{Speed: 0},
	{TargetX: 0},
	{TargetY: 0},
	{Direction: 0},
	{Bullet: 0},
	{Player_1: 0},
	{Player_1_Turret: 0},
	{Damage: 0},
	{ArmorPiercer: 0},
	{Player_1_Bullet: 0},
	{Player_1_Shot: 0},
	{Player_2_Shot: 0},
	{Player_2_Bullet: 0},
	{Trail: 0},
	{Player_1_Trail: 0},
	{Player_1_Shield: 0},
	{Player_2: 0},
	{Player_2_Turret: 0},
	{Player_2_Trail: 0},
	{Player_2_Shield: 0},
	{Player_1_LifeFont: 0},
	{Total_Score_Font: 0},
	{Enemy_Font: 0},
	{Loading_Font: 0},
	{Info_Font: 0},
	{Game_Score_Font: 0},
	{Orientation_Font: 0},
	{Level_Font: 0},
	{Reward_Font: 0},
	{Player_2_LifeFont: 0},
	{Player_1_Score_Font: 0},
	{Player_2_Score_Font: 0},
	{Level_Curtain_Font: 0},
	{Player_1_Total_Kills_Font: 0},
	{Player_2_Total_Kills_Font: 0},
	{Levels_Font: 0},
	{Text_Font: 0},
	{Constructor_Info_Font: 0},
	{Constructor_Level_Font: 0},
	{Constructor_Max_Levels_Font: 0},
	{Constructor_Text_Font: 0},
	{Type: 0},
	{Player_1_Enemy_Types_Kills_Font: 0},
	{Player_2_Enemy_Types_Kills_Font: 0},
	{Difficulty_Font: 0},
	{Total_Stars_Font: 0},
	{Levels_Score_Font: 0},
	{Cheat_Codes_Font: 0},
	{Game_End_Font: 0},
	{Difficulty_Font2: 0},
	{Difficulty_Font3: 0},
	{Button_Exit: 0},
	{Button_Facebook: 0},
	{Button_Fullscreen: 0},
	{Button_Player_1: 0},
	{Button_GooglePlus: 0},
	{Button_Info: 0},
	{Button_Menu: 0},
	{Button_MoreGames: 0},
	{Button_Music: 0},
	{Button_Pause_Player_1: 0},
	{Button_Reload: 0},
	{Button_Return: 0},
	{Button_Sound: 0},
	{Button_Start: 0},
	{Button_Twitter: 0},
	{Button_Go: 0},
	{Button_Restart: 0},
	{Button_Attack_Player_1: 0},
	{Button_Down_Player_1: 0},
	{Button_Left_Player_1: 0},
	{Button_Right_Player_1: 0},
	{Button_Up_Player_1: 0},
	{Button_Down_Player_2: 0},
	{Button_Attack_Player_2: 0},
	{Button_Left_Player_2: 0},
	{Button_Right_Player_2: 0},
	{Button_Up_Player_2: 0},
	{Button_Pause_Player_2: 0},
	{Button_Left: 0},
	{Button_Level: 0},
	{Button_Right: 0},
	{Button_BigAttack_Player_1: 0},
	{Button_Subtract: 0},
	{Button_Add: 0},
	{Button_Down_Constructor_Level: 0},
	{Button_Up_Constructor_Level: 0},
	{Button_Download: 0},
	{Button_Clean: 0},
	{Button_Delete: 0},
	{Button_Levels_Type: 0},
	{Button_Player_2: 0},
	{Button_Constructor: 0},
	{Button_Help: 0},
	{Button_No: 0},
	{Button_Yes: 0},
	{Button_Next_Level: 0},
	{Button_Back: 0},
	{Button_Delete_Game: 0},
	{Button_Replay: 0},
	{Button_Green: 0},
	{Button_Red: 0},
	{Button_Yellow: 0},
	{Button_Shop: 0},
	{Button_Chat: 0},
	{Back_Multiplayer: 0},
	{Button_Connect: 0},
	{Touch_Area: 0},
	{Collision_Level: 0},
	{Collision_Player_1: 0},
	{Collision_Player_2: 0},
	{Collision_Detector: 0},
	{Spawn_Base_Wall: 0},
	{Collision_Base: 0},
	{Enemy_Target: 0},
	{Bonus: 0},
	{Escape: 0},
	{Exploded: 0},
	{LifeRate: 0},
	{GetHit_Player: 0},
	{Enemy_AI: 0},
	{Collision_Bridge: 0},
	{Black_Screen: 0},
	{Collision_Water: 0},
	{Black_Screen2: 0},
	{Text_Paused: 0},
	{Text_Game_Over: 0},
	{Text_Your_Score: 0},
	{Text_Game_Info: 0},
	{Text_Level_Completed: 0},
	{Text_You_Won: 0},
	{Text_Game_Complete: 0},
	{Text_Select_Difficulty: 0},
	{Text_Level_Select: 0},
	{Text_Destroy_All_Progress: 0},
	{Bonus_Base: 0},
	{Bonus_Bomb: 0},
	{Player: 0},
	{Bonus_Gun: 0},
	{Bonus_Shield: 0},
	{Bonus_Life: 0},
	{Bonus_Timer: 0},
	{Bonus_Upgrade: 0},
	{Bonus_Water: 0},
	{CurrentAngle: 0},
	{Ammo: 0},
	{MaxAmmo: 0},
	{Reward: 0},
	{Enemy: 0},
	{Enemy_Bullet: 0},
	{Trunk: 0},
	{Enemy_Shot: 0},
	{Enemy_Turret: 0},
	{Enemy_Trail: 0},
	{Enemies_Life_Frame: 0},
	{Enemies_Life: 0},
	{Enemy_Star: 0},
	{Touched: 0},
	{ArrayX: 0},
	{ArrayY: 0},
	{Value: 0},
	{Block_Preload: 0},
	{Block_Image: 0},
	{Block_Preload_Selector: 0},
	{Constructor_Frame: 0},
	{Block_Image_Selector: 0},
	{Logo: 0},
	{Frame_Info_01: 0},
	{Frame_Info_02: 0},
	{Frame_Info_03: 0},
	{Frame_Info_04: 0},
	{Frame_Info_05: 0},
	{Frame_Info_06: 0},
	{Frame_Info_07: 0},
	{Frame_Info_08: 0},
	{Frame_Info_09: 0},
	{Frame_Info_10: 0},
	{Frame_Info_11: 0},
	{Frame_Info_12: 0},
	{Frame_Info_13: 0},
	{Frame_Info_14: 0},
	{Frame_Info_15: 0},
	{Frame_Info_16: 0},
	{Enemy_1_Scene: 0},
	{Enemy_2_Scene: 0},
	{Mask: 0},
	{Shot: 0},
	{Player_1_Scene: 0},
	{Player_1_Turret_Scene: 0},
	{Player_2_Scene: 0},
	{Player_2_Turret_Scene: 0},
	{Blasted_Tank_Scene: 0},
	{Bullet_Scene: 0},
	{Explosion_Tank_Scene: 0},
	{Shot_Scene: 0},
	{Smoke_Tank_Scene: 0},
	{Fire_Tank_Scene: 0},
	{Score: 0},
	{Buttons: 0},
	{Texts: 0},
	{Blocks: 0},
	{Bonuses: 0},
	{Steel: 0},
	{Curtains: 0},
	{Blocks_Preload: 0},
	{Constructor: 0},
	{Frames_Help: 0},
	{Trees: 0},
	{Cheat_Code: 0},
	{Cheat_Code_X: 0},
	{Cheat_Code_Value: 0},
	{Total_Stars: 0},
	{Difficulty_Level: 0},
	{Current_Level: 0},
	{Level: 0},
	{Level_Boss: 0},
	{Stars: 0},
	{Enemy_Sleep: 0},
	{Enemy_ID: 0},
	{Enemy_Type: 0},
	{Enemy_Level: 0},
	{Enemy_Max_Level: 0},
	{Enemy_Spawn_Point: 0},
	{Enemy_Spawn_Time: 0},
	{Max_Enemies: 0},
	{TileSize: 0},
	{AngleN: 0},
	{Base_Life: 0},
	{Steel_Base: 0},
	{Players: 0},
	{Player_1_Status: 0},
	{Player_1_God_Mode: 0},
	{Player_1_Life: 0},
	{Player_1_Total_Level_Kills: 0},
	{Player_1_Enemy_Type_1_Kills: 0},
	{Player_1_Enemy_Type_2_Kills: 0},
	{Player_1_Enemy_Type_3_Kills: 0},
	{Player_1_Enemy_Type_4_Kills: 0},
	{Player_1_Type: 0},
	{Player_1_Score: 0},
	{Player_1_Count_Score: 0},
	{Player_1_Ammo: 0},
	{Player_1_Max_Ammo: 0},
	{Player_2_Status: 0},
	{Player_2_God_Mode: 0},
	{Player_2_Life: 0},
	{Player_2_Total_Level_Kills: 0},
	{Player_2_Enemy_Type_1_Kills: 0},
	{Player_2_Enemy_Type_2_Kills: 0},
	{Player_2_Enemy_Type_3_Kills: 0},
	{Player_2_Enemy_Type_4_Kills: 0},
	{Player_2_Type: 0},
	{Player_2_Score: 0},
	{Player_2_Count_Score: 0},
	{Player_2_Ammo: 0},
	{Player_2_Max_Ammo: 0},
	{Bonus_Tank: 0},
	{Bonus_Type: 0},
	{Bonus_Random: 0},
	{Game_Status: 0},
	{Total_Score: 0},
	{Levels_Type: 0},
	{Fullscreen: 0},
	{Sound: 0},
	{Sound_Status: 0},
	{Music: 0},
	{Music_Status: 0},
	{TOKENS_EARNED: 0},
	{Current_Button_Created: 0},
	{Current_Column: 0},
	{Current_Row: 0},
	{Info_Page: 0},
	{GAME_NAME: 0},
	{DESCRIPTION: 0},
	{REDIRECT_URL: 0},
	{IMAGE: 0},
	{Max_Levels: 0},
	{Max_Levels2: 0},
	{Min_Levels: 0},
	{Constructor_Level: 0},
	{Constructor_Status: 0},
	{Level_Number: 0},
	{Total_Buttons: 0},
	{Total_Levels: 0},
	{Total_Pages: 0},
	{Levels_Page: 0},
	{Button_Rows: 0},
	{Button_Columns: 0},
	{Button_Space_Between: 0},
	{Button_Width: 0},
	{Button_Height: 0},
	{Margin_Top: 0},
	{Margin_Left: 0}
];

self.InstanceType = {
	Cursor: class extends self.ISpriteInstance {},
	Cursor_Pressed: class extends self.ISpriteInstance {},
	Gui_Big_Frame: class extends self.ISpriteInstance {},
	Map: class extends self.ISpriteInstance {},
	Gui_Controls_Player_1: class extends self.ISpriteInstance {},
	Gui_Controls_Player_2: class extends self.ISpriteInstance {},
	Gui_Level: class extends self.ISpriteInstance {},
	Frame_Glass_3: class extends self.ISpriteInstance {},
	Gui_Total_Score: class extends self.ISpriteInstance {},
	Curtain: class extends self.ISpriteInstance {},
	Gui_Curtain_Frame: class extends self.ISpriteInstance {},
	Gui_Kills_Player_1: class extends self.ISpriteInstance {},
	Gui_Kills_Player_2: class extends self.ISpriteInstance {},
	Level_Closed: class extends self.ISpriteInstance {},
	Gui_Score_Player_1: class extends self.ISpriteInstance {},
	Gui_Score_Player_2: class extends self.ISpriteInstance {},
	Gui_Life_Player_1: class extends self.ISpriteInstance {},
	Gui_Life_Player_2: class extends self.ISpriteInstance {},
	Gui_Levels_Frame: class extends self.ISpriteInstance {},
	Enemy_Tank_Icons: class extends self.ISpriteInstance {},
	Gui_Top_Frame: class extends self.ISpriteInstance {},
	Gui_Enemy: class extends self.ISpriteInstance {},
	Frame_Glass_1: class extends self.ISpriteInstance {},
	Gui_Three_Button_Frame: class extends self.ISpriteInstance {},
	Gui_Constructor_Function: class extends self.ISpriteInstance {},
	Frame_Glass_2: class extends self.ISpriteInstance {},
	Gui_One_Button_Frame: class extends self.ISpriteInstance {},
	Gui_Two_Button_Frame: class extends self.ISpriteInstance {},
	Gui_Score_Frame: class extends self.ISpriteInstance {},
	Gui_Difficulty: class extends self.ISpriteInstance {},
	Gui_Frame_0: class extends self.ISpriteInstance {},
	Frame_Glass_0: class extends self.ISpriteInstance {},
	Frame_Text: class extends self.ISpriteInstance {},
	Level_Stars: class extends self.ISpriteInstance {},
	Frame_Text_1: class extends self.ISpriteInstance {},
	Frame_Text_2: class extends self.ISpriteInstance {},
	Gui_Game_Over: class extends self.ISpriteInstance {},
	Gui_Score: class extends self.ISpriteInstance {},
	Gui_Star: class extends self.ISpriteInstance {},
	Frame_Text_3: class extends self.ISpriteInstance {},
	Frame_Text_4: class extends self.ISpriteInstance {},
	Skull: class extends self.ISpriteInstance {},
	Gui_Difficulty2: class extends self.ISpriteInstance {},
	Frame_Cheat_Codes: class extends self.ISpriteInstance {},
	Frame_Text_5: class extends self.ISpriteInstance {},
	Frame_Help_1: class extends self.ISpriteInstance {},
	Frame_Help_2: class extends self.ISpriteInstance {},
	Frame_Help_3: class extends self.ISpriteInstance {},
	Frame_Help_4: class extends self.ISpriteInstance {},
	Frame_Help_5: class extends self.ISpriteInstance {},
	Frame_Help_6: class extends self.ISpriteInstance {},
	Frame_Help_7: class extends self.ISpriteInstance {},
	Frame_Help_8: class extends self.ISpriteInstance {},
	Frame_Help_9: class extends self.ISpriteInstance {},
	Level_Star: class extends self.ISpriteInstance {},
	Frame_Line: class extends self.ISpriteInstance {},
	Loading_Line: class extends self.ITiledBackgroundInstance {},
	Prize: class extends self.ISpriteInstance {},
	Sun_Rays: class extends self.ISpriteInstance {},
	Gui_Big_Frame2: class extends self.ISpriteInstance {},
	Gui_One_Button_Frame2: class extends self.ISpriteInstance {},
	Background: class extends self.ISpriteInstance {},
	Game_Logo: class extends self.ISpriteInstance {},
	Ground: class extends self.ITiledBackgroundInstance {},
	Enemy_Spawn: class extends self.ISpriteInstance {},
	Tree_1: class extends self.ISpriteInstance {},
	Bridge: class extends self.ISpriteInstance {},
	Base: class extends self.ISpriteInstance {},
	Water: class extends self.ISpriteInstance {},
	Player_1_Spawn: class extends self.ISpriteInstance {},
	Brick: class extends self.ISpriteInstance {},
	Iron: class extends self.ISpriteInstance {},
	Steel_1: class extends self.ISpriteInstance {},
	Steel_2: class extends self.ISpriteInstance {},
	Steel_3: class extends self.ISpriteInstance {},
	Steel_4: class extends self.ISpriteInstance {},
	Player_2_Spawn: class extends self.ISpriteInstance {},
	Base_Wall: class extends self.ISpriteInstance {},
	Ground_Decor_1: class extends self.ISpriteInstance {},
	Ground_Decor_2: class extends self.ISpriteInstance {},
	Bridge_Water: class extends self.ISpriteInstance {},
	Rivets_Bottom: class extends self.ITiledBackgroundInstance {},
	Rivets_Top: class extends self.ITiledBackgroundInstance {},
	Ice: class extends self.ISpriteInstance {},
	Tree_2: class extends self.ISpriteInstance {},
	Tree_3: class extends self.ISpriteInstance {},
	Tree_4: class extends self.ISpriteInstance {},
	Stump: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	AvailableDirections: class extends self.IArrayInstance {},
	Levels: class extends self.IArrayInstance {},
	AJAX: class extends self.IInstance {},
	Levels_Stars_JSON: class extends self.IArrayInstance {},
	Levels_Stars_LOCAL: class extends self.IArrayInstance {},
	Kill_Enemies: class extends self.IArrayInstance {},
	Levels_Score_JSON: class extends self.IArrayInstance {},
	Levels_Score_LOCAL: class extends self.IArrayInstance {},
	Cheat_Codes: class extends self.IArrayInstance {},
	LocalStorage: class extends self.IInstance {},
	Explosion_Tank: class extends self.ISpriteInstance {},
	Blasted_Tank: class extends self.ISpriteInstance {},
	Explosion_Bullet: class extends self.ISpriteInstance {},
	Smoke_Tank: class extends self.IParticlesInstance {},
	Fire_Tank: class extends self.ISpriteInstance {},
	Smoke_Dead: class extends self.IParticlesInstance {},
	Glow_Dead: class extends self.ISpriteInstance {},
	Fire_Dead: class extends self.ISpriteInstance {},
	Smoke_Base: class extends self.IParticlesInstance {},
	Drown_Tank: class extends self.ISpriteInstance {},
	Explosion_Brick: class extends self.ISpriteInstance {},
	Player_1: class extends self.ISpriteInstance {},
	Player_1_Turret: class extends self.ISpriteInstance {},
	Player_1_Bullet: class extends self.ISpriteInstance {},
	Player_1_Shot: class extends self.ISpriteInstance {},
	Player_2_Shot: class extends self.ISpriteInstance {},
	Player_2_Bullet: class extends self.ISpriteInstance {},
	Player_1_Trail: class extends self.ISpriteInstance {},
	Player_1_Shield: class extends self.ISpriteInstance {},
	Player_2: class extends self.ISpriteInstance {},
	Player_2_Turret: class extends self.ISpriteInstance {},
	Player_2_Trail: class extends self.ISpriteInstance {},
	Player_2_Shield: class extends self.ISpriteInstance {},
	Player_1_LifeFont: class extends self.ISpriteFontInstance {},
	Total_Score_Font: class extends self.ISpriteFontInstance {},
	Enemy_Font: class extends self.ISpriteFontInstance {},
	Loading_Font: class extends self.ISpriteFontInstance {},
	Info_Font: class extends self.ISpriteFontInstance {},
	Game_Score_Font: class extends self.ISpriteFontInstance {},
	Orientation_Font: class extends self.ISpriteFontInstance {},
	Level_Font: class extends self.ISpriteFontInstance {},
	Reward_Font: class extends self.ISpriteFontInstance {},
	Player_2_LifeFont: class extends self.ISpriteFontInstance {},
	Player_1_Score_Font: class extends self.ISpriteFontInstance {},
	Player_2_Score_Font: class extends self.ISpriteFontInstance {},
	Level_Curtain_Font: class extends self.ISpriteFontInstance {},
	Player_1_Total_Kills_Font: class extends self.ISpriteFontInstance {},
	Player_2_Total_Kills_Font: class extends self.ISpriteFontInstance {},
	Levels_Font: class extends self.ISpriteFontInstance {},
	Text_Font: class extends self.ISpriteFontInstance {},
	Constructor_Info_Font: class extends self.ISpriteFontInstance {},
	Constructor_Level_Font: class extends self.ISpriteFontInstance {},
	Constructor_Max_Levels_Font: class extends self.ISpriteFontInstance {},
	Constructor_Text_Font: class extends self.ISpriteFontInstance {},
	Player_1_Enemy_Types_Kills_Font: class extends self.ISpriteFontInstance {},
	Player_2_Enemy_Types_Kills_Font: class extends self.ISpriteFontInstance {},
	Difficulty_Font: class extends self.ISpriteFontInstance {},
	Total_Stars_Font: class extends self.ISpriteFontInstance {},
	Levels_Score_Font: class extends self.ISpriteFontInstance {},
	Cheat_Codes_Font: class extends self.ISpriteFontInstance {},
	Game_End_Font: class extends self.ISpriteFontInstance {},
	Difficulty_Font2: class extends self.ISpriteFontInstance {},
	Difficulty_Font3: class extends self.ISpriteFontInstance {},
	Button_Exit: class extends self.ISpriteInstance {},
	Button_Facebook: class extends self.ISpriteInstance {},
	Button_Fullscreen: class extends self.ISpriteInstance {},
	Button_Player_1: class extends self.ISpriteInstance {},
	Button_GooglePlus: class extends self.ISpriteInstance {},
	Button_Info: class extends self.ISpriteInstance {},
	Button_Menu: class extends self.ISpriteInstance {},
	Button_MoreGames: class extends self.ISpriteInstance {},
	Button_Music: class extends self.ISpriteInstance {},
	Button_Pause_Player_1: class extends self.ISpriteInstance {},
	Button_Reload: class extends self.ISpriteInstance {},
	Button_Return: class extends self.ISpriteInstance {},
	Button_Sound: class extends self.ISpriteInstance {},
	Button_Start: class extends self.ISpriteInstance {},
	Button_Twitter: class extends self.ISpriteInstance {},
	Button_Go: class extends self.ISpriteInstance {},
	Button_Restart: class extends self.ISpriteInstance {},
	Button_Attack_Player_1: class extends self.ISpriteInstance {},
	Button_Down_Player_1: class extends self.ISpriteInstance {},
	Button_Left_Player_1: class extends self.ISpriteInstance {},
	Button_Right_Player_1: class extends self.ISpriteInstance {},
	Button_Up_Player_1: class extends self.ISpriteInstance {},
	Button_Down_Player_2: class extends self.ISpriteInstance {},
	Button_Attack_Player_2: class extends self.ISpriteInstance {},
	Button_Left_Player_2: class extends self.ISpriteInstance {},
	Button_Right_Player_2: class extends self.ISpriteInstance {},
	Button_Up_Player_2: class extends self.ISpriteInstance {},
	Button_Pause_Player_2: class extends self.ISpriteInstance {},
	Button_Left: class extends self.ISpriteInstance {},
	Button_Level: class extends self.ISpriteInstance {},
	Button_Right: class extends self.ISpriteInstance {},
	Button_BigAttack_Player_1: class extends self.ISpriteInstance {},
	Button_Subtract: class extends self.ISpriteInstance {},
	Button_Add: class extends self.ISpriteInstance {},
	Button_Down_Constructor_Level: class extends self.ISpriteInstance {},
	Button_Up_Constructor_Level: class extends self.ISpriteInstance {},
	Button_Download: class extends self.ISpriteInstance {},
	Button_Clean: class extends self.ISpriteInstance {},
	Button_Delete: class extends self.ISpriteInstance {},
	Button_Levels_Type: class extends self.ISpriteInstance {},
	Button_Player_2: class extends self.ISpriteInstance {},
	Button_Constructor: class extends self.ISpriteInstance {},
	Button_Help: class extends self.ISpriteInstance {},
	Button_No: class extends self.ISpriteInstance {},
	Button_Yes: class extends self.ISpriteInstance {},
	Button_Next_Level: class extends self.ISpriteInstance {},
	Button_Back: class extends self.ISpriteInstance {},
	Button_Delete_Game: class extends self.ISpriteInstance {},
	Button_Replay: class extends self.ISpriteInstance {},
	Button_Green: class extends self.ISpriteInstance {},
	Button_Red: class extends self.ISpriteInstance {},
	Button_Yellow: class extends self.ISpriteInstance {},
	Button_Shop: class extends self.ISpriteInstance {},
	Button_Chat: class extends self.ISpriteInstance {},
	Back_Multiplayer: class extends self.ISpriteInstance {},
	Button_Connect: class extends self.ISpriteInstance {},
	Touch_Area: class extends self.ISpriteInstance {},
	Collision_Level: class extends self.ISpriteInstance {},
	Collision_Player_1: class extends self.ISpriteInstance {},
	Collision_Player_2: class extends self.ISpriteInstance {},
	Collision_Detector: class extends self.ISpriteInstance {},
	Spawn_Base_Wall: class extends self.ISpriteInstance {},
	Collision_Base: class extends self.ISpriteInstance {},
	Enemy_Target: class extends self.ISpriteInstance {},
	Enemy_AI: class extends self.ISpriteInstance {},
	Collision_Bridge: class extends self.ISpriteInstance {},
	Black_Screen: class extends self.ISpriteInstance {},
	Collision_Water: class extends self.ISpriteInstance {},
	Black_Screen2: class extends self.ISpriteInstance {},
	Text_Paused: class extends self.ISpriteInstance {},
	Text_Game_Over: class extends self.ISpriteInstance {},
	Text_Your_Score: class extends self.ISpriteInstance {},
	Text_Game_Info: class extends self.ISpriteInstance {},
	Text_Level_Completed: class extends self.ISpriteInstance {},
	Text_You_Won: class extends self.ISpriteInstance {},
	Text_Game_Complete: class extends self.ISpriteInstance {},
	Text_Select_Difficulty: class extends self.ISpriteInstance {},
	Text_Level_Select: class extends self.ISpriteInstance {},
	Text_Destroy_All_Progress: class extends self.ISpriteInstance {},
	Bonus_Base: class extends self.ISpriteInstance {},
	Bonus_Bomb: class extends self.ISpriteInstance {},
	Bonus_Gun: class extends self.ISpriteInstance {},
	Bonus_Shield: class extends self.ISpriteInstance {},
	Bonus_Life: class extends self.ISpriteInstance {},
	Bonus_Timer: class extends self.ISpriteInstance {},
	Bonus_Upgrade: class extends self.ISpriteInstance {},
	Bonus_Water: class extends self.ISpriteInstance {},
	Bonus: class extends self.ISpriteInstance {},
	Enemy: class extends self.ISpriteInstance {},
	Enemy_Bullet: class extends self.ISpriteInstance {},
	Enemy_Shot: class extends self.ISpriteInstance {},
	Enemy_Turret: class extends self.ISpriteInstance {},
	Enemy_Trail: class extends self.ISpriteInstance {},
	Enemies_Life_Frame: class extends self.ISpriteInstance {},
	Enemies_Life: class extends self.ITiledBackgroundInstance {},
	Enemy_Star: class extends self.ISpriteInstance {},
	Block_Preload: class extends self.ISpriteInstance {},
	Block_Image: class extends self.ISpriteInstance {},
	Block_Preload_Selector: class extends self.ISpriteInstance {},
	Constructor_Frame: class extends self.ISpriteInstance {},
	Block_Image_Selector: class extends self.ISpriteInstance {},
	Logo: class extends self.ISpriteInstance {},
	Frame_Info_01: class extends self.ISpriteInstance {},
	Frame_Info_02: class extends self.ISpriteInstance {},
	Frame_Info_03: class extends self.ISpriteInstance {},
	Frame_Info_04: class extends self.ISpriteInstance {},
	Frame_Info_05: class extends self.ISpriteInstance {},
	Frame_Info_06: class extends self.ISpriteInstance {},
	Frame_Info_07: class extends self.ISpriteInstance {},
	Frame_Info_08: class extends self.ISpriteInstance {},
	Frame_Info_09: class extends self.ISpriteInstance {},
	Frame_Info_10: class extends self.ISpriteInstance {},
	Frame_Info_11: class extends self.ISpriteInstance {},
	Frame_Info_12: class extends self.ISpriteInstance {},
	Frame_Info_13: class extends self.ISpriteInstance {},
	Frame_Info_14: class extends self.ISpriteInstance {},
	Frame_Info_15: class extends self.ISpriteInstance {},
	Frame_Info_16: class extends self.ISpriteInstance {},
	Enemy_1_Scene: class extends self.ISpriteInstance {},
	Enemy_2_Scene: class extends self.ISpriteInstance {},
	Mask: class extends self.ISpriteInstance {},
	Player_1_Scene: class extends self.ISpriteInstance {},
	Player_1_Turret_Scene: class extends self.ISpriteInstance {},
	Player_2_Scene: class extends self.ISpriteInstance {},
	Player_2_Turret_Scene: class extends self.ISpriteInstance {},
	Blasted_Tank_Scene: class extends self.ISpriteInstance {},
	Bullet_Scene: class extends self.ISpriteInstance {},
	Explosion_Tank_Scene: class extends self.ISpriteInstance {},
	Shot_Scene: class extends self.ISpriteInstance {},
	Smoke_Tank_Scene: class extends self.IParticlesInstance {},
	Fire_Tank_Scene: class extends self.ISpriteInstance {},
	Score: class extends self.IJSONInstance {},
	Buttons: class extends self.ISpriteInstance {},
	Texts: class extends self.ISpriteInstance {},
	Blocks: class extends self.ISpriteInstance {},
	Bonuses: class extends self.ISpriteInstance {},
	Steel: class extends self.ISpriteInstance {},
	Curtains: class extends self.ISpriteInstance {},
	Blocks_Preload: class extends self.ISpriteInstance {},
	Constructor: class extends self.ISpriteInstance {},
	Frames_Help: class extends self.ISpriteInstance {},
	Trees: class extends self.ISpriteInstance {}
}